name: Generate TOC

on:
  push:
    paths:
      - '**.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Table of Contents
        run: |
          python scripts/generate_toc.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-update TOC"
          git push
