name: Generate PDF Documentation

on:
  workflow_dispatch:
  push:
    branches: [ gh-pages ]

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate LaTeX from filelist.txt
        run: |
          mkdir -p output
          pandoc $(cat filelist.txt) -s --toc -o output/final-doc.tex

      - name: Upload LaTeX source
        uses: actions/upload-artifact@v4
        with:
          name: documentation-latex
          path: output/final-doc.tex

